title: Crisel Suarez
subtitle: Crisel Suarez website
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Papers
      url: /blog
    - text: CV
      url: /gallery
    - text: Presentations
     # url : /shop
    - text: Outreach
      url : /outreach
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: about_me_image.png
author: Crisel Suarez
author_bio: |
    ¡Hola! My name is Crisel Suarez. I am a Physics PhD candidate at (Vanderbilt University)[https://as.vanderbilt.edu/physics-astronomy/] and (Smithsonian Astrophysical Observatory Predoctoral Fellow)[https://lweb.cfa.harvard.edu/fellowships/prrc]. I grew up in Mexico City and Austin, TX. I am fully bilingual in both Spanish and English. I earned my Bachelor’s of Science and majored in Mathematics and minored in Global Studies and Physics at a small liberal arts school called (St. Edward’s University)[https://www.stedwards.edu/]. I was a (McNair Scholar)[https://www.stedwards.edu/mcnair-scholars-program] at St. Edward’s University and pursued all types of research; from Computer Science looking at the expected values of properties in the game of __Monopoly__ (with [Dr. Michael Kart](https://www.stedwards.edu/directory/employees/kart-michael-u)), Mathematics looking at the tetrominoes (Tetris pieces) and how they form gaps and make you lose at __Tetris__ (with (Dr. Jason Callahan)[https://www.stedwards.edu/directory/employees/callahan-jason-t]), and Science Education in quantifying science literacy in undergraduates students with (with (Dr. Paul Walter)[https://scholar.google.com/citations?user=MdO0-xMAAAAJ&hl=en]. I also took a Nanotechnologies and Nanofabrication certification from the Nanomanufacturing Systems Center ((NASCENT)[https://nascent.utexas.edu/graduate-certificate-experiential-nanotechnologies-big-data]) at University of Texas at Austin. <br>
    
    After graduating from St. Edward’s University, I went to pursue my Masters of Science in Physics at (Fisk University)[https://www.fisk.edu/] as part of the (Fisk-Vanderbilt Masters to PhD program)[https://www.fisk-vanderbilt-bridge.org/]. At Fisk, I was part of Dr. Arnold Burger’s (Materials Science and Applications Group)[https://www.fisk-vanderbilt-bridge.org/msag] where I studied the chemical composition of high energy crystal scintillators using Vanderbilt’s University high performance computing (ACCRE)[https://www.accre.vanderbilt.edu/] facilities. <br>
    
    During the summers as a Masters student, I had the opportunity to work with (Dr. Christopher S. Moore)[https://www.christophermoorephd.com/] at the (Center for Astrophysics | Harvard & Smithsonian)[https://cfa.harvard.edu/] in the Solar Stellar X-ray Group ((SSXG)[https://lweb.cfa.harvard.edu/hea/sss/sun.html])  as part of the Fisk-Vanderbilt-CfA Latino Initiative Program (now CfA Research Experiences in Astronomy, Technology, & Engineering (CREATE)[https://pweb.cfa.harvard.edu/opportunities/graduate-undergraduate-programs/latino-initiative-program]) program. I worked on analyzing beautiful high energy events in the Sun called solar flares. As part of PhD work at Vanderbilt University, I continued to examined ~30 soft x-ray (SXR) flares observed with the Miniature X-ray Solar Spectrometer (MinXSS-1) and derived changes in temperature, volume emission measure and elemental abundances as a function of time with parametric spectral fits. I continue to research solar flares and look for Quasi-Periodic Pulsations (QPPs) in flares with different instruments including Hinode/X-ray Telescope (Hinode/XRT), Solar Dynamic Observatory/Atmospheric Imaging Assembly (SDO/AIA), Geostationary Operational Environmental Satellite (GOES), Miniature X-ray Solar Spectrometer- 1 and 2 (MinXSS-1&2) and Dual Aperture X-ray Solar Spectrometer (DAXSS). I have also used the Hydrodynamic Radiation (HYDRAD) model to synthesize Extreme Ultraviolet (EUV) and soft x-ray (SXR) emission in solar flares. <br>
    
    I also enjoy engaging in science outreach events, promoting research, curiosity, creativity and mentoring the next generation of scientists! <br>
    
    When I have some rare free time, I like going to museums, shows, trying new foods, and traveling! <br>
    
author_email: "criselsuarez[at]gmail[dot]com"
#author_location: India
author_website_url: "https://criselsuarez.github.io"
typewrite-text: Welcome to my website! # devlopr is a jekyll framework built for developers. You can edit this in _config.yml file
hero_cover_img: SDO-AIA3.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Center for Astrophyscis Harvard & Smithsonian
              company_logo: cfa_logo_vertical.jpg
              company_url: https://www.cfa.harvard.edu/
              designation: Predoctoral Fellow
              #description: Worked on various Google Products
              visibility: true

# Education
author_education_details:
              - college_logo: STE-austin.jpg
                college_name: St. Edwards University
                college_url: https://www.stedwards.edu/
                college_degree: Mathematics
                description: Bachelor of Science
                visibility: true
              - college_logo: FISK_LOGO2.png
                college_name: Fisk University
                college_url: https://www.fisk.edu/
                college_degree: Physics
                description: Masters of Science
                visibility: true
              - college_logo: VandyLogo2.png
                college_name: Vanderbilt University
                college_url: https://www.vanderbilt.edu/
                college_degree: Physics
                description: Doctor of Philosophy
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
#twitter_username: johndoe
github_username:  criselsuarez
#facebook_username: johndoe
linkedin_username: crisel-suarez-0714
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: criselsuarez

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: criselsuarez[@]gmail[dot]com # johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: CriselSuarez
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
